/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team7.client;

import javafx.util.Duration;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;

import javafx.scene.media.MediaPlayer;

import edu.duke.ece651.team7.client.controller.ErrorReporter;
import edu.duke.ece651.team7.client.controller.LoginSignupController;

public class App extends Application {
  private static final Logger logger = LoggerFactory.getLogger(App.class);

  public static void main(String[] args) {
    logger.info("GUI client running");
    launch(args);
  }

  @Override
  public void start(Stage primaryStage) {
    try {
      //set the background music
      MediaPlayer backgroundPlayer = MusicFactory.createBackgroundPlayer();
      backgroundPlayer.setAutoPlay(true);
      backgroundPlayer.setCycleCount(MediaPlayer.INDEFINITE);
      backgroundPlayer.setOnEndOfMedia(() -> {
        backgroundPlayer.seek(Duration.ZERO);
      });

      Thread.setDefaultUncaughtExceptionHandler(new ErrorReporter());
      Scene scene = LoginSignupController.getScene();
      primaryStage.setScene(scene);
      primaryStage.show();
    } catch (Exception e) {
      logger.error(e.getMessage(), e);
    }
  }

}
